name: Build for macOS

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/macos.yml'
      - 'sql/**'
      - 'pgtap/**'
      - 'tools/testers/**'
      - 'CMakeLists.txt'

    branches-ignore:
      - 'gh-pages'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    # disbale action, TODO install plpython3u.control
    if: ${{ false }}
    name: macos
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        release: [Debug, Release]
        os: [macos-latest, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          brew install postgresql@14 asio glpk rapidjson

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.release }} -DWITH_DOC=OFF ..

      - name: Build
        run: |
          cd build
          make -j
          make install

      - name: Install pgTAP
        run: |
          git clone https://github.com/theory/pgtap.git pgTapExtension
          cd pgTapExtension
          make -j
          make install
          cpan TAP::Parser::SourceHandler::pgTAP
          ln -s $(find `brew --prefix` -name pg_prove) symlink it into $(brew --prefix)/bin

      - name: Test
        run: |
          export PATH=$(brew --prefix)/Cellar/perl/$(perl -e 'print substr($^V, 1)')/bin:$PATH
          pg_ctl -D $(brew --prefix)/var/postgresql@14 start
          createuser -s postgres
          bash ./tools/testers/pg_prove_tests.sh -U postgres -p 5432
